server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: USERSERVICES
          uri: lb://USERSERVICES
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATINGSERVICES
          uri: lb://RATINGSERVICES
          predicates:
            - Path=/ratings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
